-- Add new columns to existing students table
ALTER TABLE students
ADD COLUMN phone VARCHAR(20) DEFAULT '',
ADD COLUMN gender VARCHAR(10) DEFAULT '',
ADD COLUMN dob DATE DEFAULT NULL,
ADD COLUMN enrollmentDate DATE DEFAULT NULL,
ADD COLUMN status VARCHAR(20) DEFAULT 'Active',
ADD COLUMN address TEXT,
ADD COLUMN createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP;
